alias gst='git status'
alias gall='git add .'
alias gcm='git commit -m'
alias gp='git push'
alias gl='git pull'
alias art="php artisan"
alias migrate="php artisan migrate"
alias routes='php artisan route:list'
alias tinker='php artisan tinker'
alias gdiff='git diff master origin/master'
